//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contensive.Addons.aoIntercom.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contensive.Addons.aoIntercom.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to window.intercomSettings = {
        ///    app_id: &quot;{0}&quot;,
        ///    email: &quot;{1}&quot;, // Email address
        ///    user_hash: &quot;{2}&quot; // HMAC using SHA-256
        ///};
        ///(function(){var w=window;var ic=w.Intercom;if(typeof ic===&quot;function&quot;){ic(&apos;reattach_activator&apos;);ic(&apos;update&apos;,intercomSettings);}else{var d=document;var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};w.Intercom=i;function l(){var s=d.createElement(&apos;script&apos;);s.type=&apos;text/javascript&apos;;s.async=true;s.src=&apos;https://widget.intercom.io/widget/hajvz7zq&apos;;var x=d.get [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IntercommAuthScript {
            get {
                return ResourceManager.GetString("IntercommAuthScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to window.intercomSettings = {app_id: {0}};
        ///(function(){var w=window;var ic=w.Intercom;if(typeof ic===&quot;function&quot;){ic(&apos;reattach_activator&apos;);ic(&apos;update&apos;,intercomSettings);}else{var d=document;var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};w.Intercom=i;function l(){var s=d.createElement(&apos;script&apos;);s.type=&apos;text/javascript&apos;;s.async=true;s.src=&apos;https://widget.intercom.io/widget/&apos; + APP_ID;var x=d.getElementsByTagName(&apos;script&apos;)[0];x.parentNode.insertBefore(s,x);}if(w.attachEvent){w.attachE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IntercommNonAuthScript {
            get {
                return ResourceManager.GetString("IntercommNonAuthScript", resourceCulture);
            }
        }
    }
}
